version: '2'

services:

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    ports:
      - '3306:3306'

  phpmyadmin:
    image: 'bitnami/phpmyadmin:latest'
    ports:
      - '8080:80'
    depends_on:
      - mariadb
    volumes:
      - 'phpmyadmin_data:/bitnami'

  jupyter:
    command: ["jupyter", "notebook", "--allow-root", "--ip=0.0.0.0", "--no-browser"]
    build:
        context: jupyter_image
    depends_on:
        - phpmyadmin
    # env_file:
    #     - jupyter_image.env
    volumes:
        - jupyter_data:/app/python_scripts
    ports:
        - 8888:8888

volumes:
  mariadb_data:
    driver: local
  phpmyadmin_data:
    driver: local
  jupyter_data:
    driver: local
