version: '2'

services:

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './mysql_persist:/bitnami'
    ports:
      - '3306:3306'

  phpmyadmin:
    image: 'bitnami/phpmyadmin:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:80'
    depends_on:
      - mariadb
    volumes:
      - './phpmyadmin_persist:/bitnami'

  jupyter:
    command: ["jupyter", "notebook", "--allow-root", "--ip=0.0.0.0", "--no-browser"]
    build:
        context: jupyter_image
    depends_on:
        - phpmyadmin
    # env_file:
    #     - jupyter_image.env
    volumes:
        - ./python_scripts:/app/python_scripts
    ports:
        - 8888:8888
